# version 0.4
services:
  postgres:
    image: postgres
    container_name: kaspool-db
    networks:
      - backend    
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
      - .env
    restart: always

  kaspool-app:
    image: ghcr.io/coinchimp/kaspool-app:v2408.1b-coinchimp240810
    container_name: kaspool-app
    depends_on:
      - postgres
      - kaspool-monitor
      - pushgateway
    ports:
      - "7777:7777"
    networks:
      - backend
    volumes:
      - ./config:/app/config 
      - ./wasm:/app/wasm         
    env_file:
      - .env
    restart: always

  kaspool-monitor:
    image: ghcr.io/coinchimp/kaspool-monitor:v2408.1b-main
    container_name: kaspool-monitor
    depends_on:
      - postgres
    networks:
      - backend       
    env_file:
      - .env
    restart: always

  kaspool-payment:
    image: ghcr.io/coinchimp/kaspool-payment:v2408.1b-main
    container_name: kaspool-payment   
    depends_on:
      - postgres
    volumes:
      - ./config:/app/config
      - ./wasm:/app/wasm       
    networks:
      - backend       
    env_file:
      - .env
    restart: always

  prometheus:
    image: prom/prometheus
    container_name: kaspool-prmths
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
#      - ./prometheus_data:/prometheus
    networks:
      - backend       
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    restart: always

  pushgateway:
    image: prom/pushgateway
    container_name: kaspool-pushgateway   
    networks:
      - backend
    restart: always

  nginx:
    container_name: kaspool-nginx
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
#      - ./htpasswd:/etc/nginx/.htpasswd
    ports:
      - "8080:8080"     
    networks:
      - backend      
    depends_on:
      - prometheus
      - kaspool-monitor    
    restart: always  

  # postgres-backup:
  #   image: kaspool-backup:0.4
  #   container_name: kaspool-backup
  #   depends_on:
  #     - postgres
  #   env_file:
  #     - .env
  #   volumes:
  #     - ./backup/files:/backup/files
  #   networks:
  #     - backend
  #   restart: always

networks:
  backend:
    driver: bridge
